name: SolidsPy_experiences
channels:
  - default
dependencies:
  - python>=3.6
  - numpy
  - scipy
  - matplotlib>=2.0
  - sympy
  - jupyter
  - ipython
  - spyder
  - ipykernel
  - pandas
  - geopandas
  - json
  - bokeh
  - pip
  - pip:
    - meshio==3.0
    - solidspy==1.0.16
